server.port=${PORT:8081}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/prestaya}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root123}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

exchange.api.key=${EXCHANGE_API_KEY:80aba1836ba9c7ae593462ca}
exchange.api.base-url=https://v6.exchangerate-api.com/v6
